server:
  port:  8080

  spring:
    profiles: test
---
server:
  port:  8081

  spring :
    profiles: dev
---
server:
  port:  8082

  spring :
    profiles: pro
---
  spring:
   profiles:
      active: pro
