#配置数据库信息
spring:
  datasource:
    url: jdbc:mysql:///test
    username: root
    password: 13538026482
    driver-class-name: com.mysql.cj.jdbc.Driver


 #配置mybaties，xml做法
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml  #mapper映射文件路径